---
title: "IAKA_doublet"
author: "Javier Villegas"
date: "2025-11-28"
output: html_document
---


```{r setup, include=FALSE}
set.seed(seed = 42)
library(Seurat)
library(tidyverse)
library(DoubletFinder)
options(future.globals.maxSize = 6000 * 1024^2)
#Creating the output folder in case it's not there 
# output_dir <- paste0(getwd(),"/output/")
#     if (!dir.exists(output_dir)) {
#       dir.create(output_dir, recursive = T)
#     }
```




```{r DoubletFinder}
#Loading precreated file
# 
KA_seurat_prefiltered <- readRDS("../QC/KA_seurat_prefiltered.rds")

srat_QC <- subset(KA_seurat_prefiltered, subset = percent.mt<1 & nFeature_RNA>500)

srat_Epi1 <- subset(srat_QC,subset=sample.origin=="Epi1")
#Pre-process sample Seurat object
srat_Epi1 <- SCTransform(srat_Epi1,verbose=F)
srat_Epi1 <- RunPCA(srat_Epi1, features = VariableFeatures(object = srat_Epi1))
srat_Epi1 <- FindNeighbors(srat_Epi1, dims = 1:20)
srat_Epi1 <- FindClusters(srat_Epi1, resolution = 1)
srat_Epi1 <- RunTSNE(srat_Epi1)
srat_Epi1 <- RunUMAP(srat_Epi1, dims = 1:20)

#pK Identification
sweep.res.list_Epi1 <- paramSweep(srat_Epi1, PCs = 1:20, sct = T)
sweep.stats_Epi1 <- summarizeSweep(sweep.res.list_Epi1, GT = FALSE)
 
pK_Epi1 <- sweep.stats_Epi1 %>% filter(BCreal == max(BCreal)) %>% select(pK) 
pK_Epi1<- as.numeric(as.character(pK_Epi1[[1]]))
## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop_Epi1 <- modelHomotypic(srat_Epi1$SCT_snn_res.1)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi_Epi1 <- round(0.016*nrow(srat_Epi1@meta.data))  ## Assuming 3.5% doublet formation rate - tailor for your dataset
nExp_poi.adj_Epi1 <- round(nExp_poi_Epi1*(1-homotypic.prop_Epi1))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
srat_Epi1 <- doubletFinder(srat_Epi1, PCs = 1:20, pN = 0.25, pK = pK_Epi1, nExp = nExp_poi_Epi1, reuse.pANN = FALSE, sct = T)


saveRDS(srat_Epi1,"srat_Epi1.rds")
to_keep <- c(colnames(srat_Epi1@meta.data),"UMAP_1","UMAP_2")
df_out<- FetchData(srat_Epi1,to_keep) %>% rownames_to_column("cell")
out_name <- paste0("./Epi1_",Sys.Date(),"_cell_metadata.tsv.gz")
write_csv(df_out,out_name)
##################################################################################

srat_Epi2 <- subset(srat_QC,subset=sample.origin=="Epi2")
#Pre-process sample Seurat object
srat_Epi2 <- SCTransform(srat_Epi2,verbose=F)
srat_Epi2 <- RunPCA(srat_Epi2, features = VariableFeatures(object = srat_Epi2))
srat_Epi2 <- FindNeighbors(srat_Epi2, dims = 1:20)
srat_Epi2 <- FindClusters(srat_Epi2, resolution = 1)
srat_Epi2 <- RunTSNE(srat_Epi2)
srat_Epi2 <- RunUMAP(srat_Epi2, dims = 1:20)

#pK Identification
sweep.res.list_Epi2 <- paramSweep(srat_Epi2, PCs = 1:10, sct = T)
sweep.stats_Epi2 <- summarizeSweep(sweep.res.list_Epi2, GT = FALSE)

pK_Epi2 <- sweep.stats_Epi2 %>% filter(BCreal == max(BCreal)) %>% select(pK) 
pK_Epi2<- as.numeric(as.character(pK_Epi2[[1]]))
## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop_Epi2 <- modelHomotypic(srat_Epi2$SCT_snn_res.1)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi_Epi2 <- round(0.016*nrow(srat_Epi2@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj_Epi2 <- round(nExp_poi_Epi2*(1-homotypic.prop_Epi2))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
srat_Epi2 <- doubletFinder(srat_Epi2, PCs = 1:10, pN = 0.25, pK = pK_Epi2, nExp = nExp_poi_Epi2, reuse.pANN = FALSE, sct = T)


saveRDS(srat_Epi2,"srat_Epi2.rds")
to_keep <- c(colnames(srat_Epi2@meta.data),"UMAP_1","UMAP_2")
df_out<- FetchData(srat_Epi2,to_keep) %>% rownames_to_column("cell")
out_name <- paste0("./Epi2_",Sys.Date(),"_cell_metadata.tsv.gz")
write_csv(df_out,out_name)



################################################################################################################
srat_Epi3 <- subset(srat_QC,subset=sample.origin=="Epi3")
#Pre-process sample Seurat object
srat_Epi3 <- SCTransform(srat_Epi3,verbose=F)
srat_Epi3 <- RunPCA(srat_Epi3, features = VariableFeatures(object = srat_Epi3))
srat_Epi3 <- FindNeighbors(srat_Epi3, dims = 1:20)
srat_Epi3 <- FindClusters(srat_Epi3, resolution = 1)
srat_Epi3 <- RunTSNE(srat_Epi3)
srat_Epi3 <- RunUMAP(srat_Epi3, dims = 1:20)

#pK Identification
sweep.res.list_Epi3 <- paramSweep(srat_Epi3, PCs = 1:10, sct = T)
sweep.stats_Epi3 <- summarizeSweep(sweep.res.list_Epi3, GT = FALSE)
bcmvn_Epi3 <- find.pK(sweep.stats_Epi3)

pK_Epi3 <- sweep.stats_Epi3 %>% filter(BCreal == max(BCreal)) %>% select(pK) 
pK_Epi3<- as.numeric(as.character(pK_Epi3[[1]]))
## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop_Epi3 <- modelHomotypic(srat_Epi3$SCT_snn_res.1)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi_Epi3 <- round(0.024*nrow(srat_Epi3@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj_Epi3 <- round(nExp_poi_Epi3*(1-homotypic.prop_Epi3))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
srat_Epi3 <- doubletFinder(srat_Epi3, PCs = 1:10, pN = 0.25, pK = pK_Epi3, nExp = nExp_poi_Epi3, reuse.pANN = FALSE, sct = T)


saveRDS(srat_Epi3,"srat_Epi3.rds")
to_keep <- c(colnames(srat_Epi3@meta.data),"UMAP_1","UMAP_2")
df_out<- FetchData(srat_Epi3,to_keep) %>% rownames_to_column("cell")
out_name <- paste0("./srat_Epi3_",Sys.Date(),"_cell_metadata.tsv.gz")
write_csv(df_out,out_name)
################################################################################################################
srat_Epi4 <- subset(srat_QC,subset=sample.origin=="Epi4")
#Pre-process sample Seurat object
srat_Epi4 <- SCTransform(srat_Epi4,verbose=F)
srat_Epi4 <- RunPCA(srat_Epi4, features = VariableFeatures(object = srat_Epi4))
srat_Epi4 <- FindNeighbors(srat_Epi4, dims = 1:20)
srat_Epi4 <- FindClusters(srat_Epi4, resolution = 1)
srat_Epi4 <- RunTSNE(srat_Epi4)
srat_Epi4 <- RunUMAP(srat_Epi4, dims = 1:20)

#pK Identification
sweep.res.list_Epi4 <- paramSweep(srat_Epi4, PCs = 1:10, sct = T)
sweep.stats_Epi4 <- summarizeSweep(sweep.res.list_Epi4, GT = FALSE)
bcmvn_Epi4 <- find.pK(sweep.stats_Epi4)

pK_Epi4 <- sweep.stats_Epi4 %>% filter(BCreal == max(BCreal)) %>% select(pK) 
pK_Epi4 <- as.numeric(as.character(pK_Epi4[[1]]))
## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop_Epi4 <- modelHomotypic(srat_Epi4$SCT_snn_res.1)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi_Epi4 <- round(0.024*nrow(srat_Epi4@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj_Epi4 <- round(nExp_poi_Epi4*(1-homotypic.prop_Epi4))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
srat_Epi4 <- doubletFinder(srat_Epi4, PCs = 1:10, pN = 0.25, pK = pK_Epi4, nExp = nExp_poi_Epi4, reuse.pANN = FALSE, sct = T)


saveRDS(srat_Epi4,"srat_Epi4.rds")
to_keep <- c(colnames(srat_Epi4@meta.data),"UMAP_1","UMAP_2")
df_out<- FetchData(srat_Epi4,to_keep) %>% rownames_to_column("cell")
out_name <- paste0("./Epi4_",Sys.Date(),"_cell_metadata.tsv.gz")
write_csv(df_out,out_name)

# ###############################################################################################
srat_Control1 <- subset(srat_QC,subset=sample.origin=="Control1")
#Pre-process sample Seurat object
srat_Control1 <- SCTransform(srat_Control1,verbose=F)
srat_Control1 <- RunPCA(srat_Control1, features = VariableFeatures(object = srat_Control1))
srat_Control1 <- FindNeighbors(srat_Control1, dims = 1:20)
srat_Control1 <- FindClusters(srat_Control1, resolution = 1)
srat_Control1 <- RunTSNE(srat_Control1)
srat_Control1 <- RunUMAP(srat_Control1, dims = 1:20)

#pK Identification
sweep.res.list_Control1 <- paramSweep(srat_Control1, PCs = 1:10, sct = T)
sweep.stats_Control1 <- summarizeSweep(sweep.res.list_Control1, GT = FALSE)
bcmvn_Control1 <- find.pK(sweep.stats_Control1)

pK_Control1 <- sweep.stats_Control1 %>% filter(BCreal == max(BCreal)) %>% select(pK) 
pK_Control1 <- as.numeric(as.character(pK_Control1[[1]]))
## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop_Control1 <- modelHomotypic(srat_Control1$SCT_snn_res.1)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi_Control1 <- round(0.024*nrow(srat_Control1@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj_Control1 <- round(nExp_poi_Control1*(1-homotypic.prop_Control1))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
srat_Control1 <- doubletFinder(srat_Control1, PCs = 1:10, pN = 0.25, pK = pK_Control1, nExp = nExp_poi_Control1, reuse.pANN = FALSE, sct = T)

saveRDS(srat_Control1,"srat_Control1.rds")
to_keep <- c(colnames(srat_Control1@meta.data),"UMAP_1","UMAP_2")
df_out<- FetchData(srat_Control1,to_keep) %>% rownames_to_column("cell")
out_name <- paste0("./Control1_",Sys.Date(),"_cell_metadata.tsv.gz")
write_csv(df_out,out_name)

###############################################################################################
srat_Control2 <- subset(srat_QC,subset=sample.origin=="Control2")
#Pre-process sample Seurat object
srat_Control2 <- SCTransform(srat_Control2,verbose=F)
srat_Control2 <- RunPCA(srat_Control2, features = VariableFeatures(object = srat_Control2))
srat_Control2 <- FindNeighbors(srat_Control2, dims = 1:20)
srat_Control2 <- FindClusters(srat_Control2, resolution = 1)
srat_Control2 <- RunTSNE(srat_Control2)
srat_Control2 <- RunUMAP(srat_Control2, dims = 1:20)

#pK Identification
sweep.res.list_Control2 <- paramSweep(srat_Control2, PCs = 1:10, sct = T)
sweep.stats_Control2 <- summarizeSweep(sweep.res.list_Control2, GT = FALSE)
bcmvn_Control2 <- find.pK(sweep.stats_Control2)

pK_Control2 <- sweep.stats_Control2 %>% filter(BCreal == max(BCreal)) %>% select(pK) 
pK_Control2 <- as.numeric(as.character(pK_Control2[[1]]))

## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop_Control2 <- modelHomotypic(srat_Control2$SCT_snn_res.1)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi_Control2 <- round(0.16*nrow(srat_Control2@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj_Control2 <- round(nExp_poi_Control2*(1-homotypic.prop_Control2))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
srat_Control2 <- doubletFinder(srat_Control2, PCs = 1:10, pN = 0.25, pK = pK_Control2, nExp = nExp_poi_Control2, reuse.pANN = FALSE, sct = T)

saveRDS(srat_Control2,"srat_Control2.rds")
to_keep <- c(colnames(srat_Control2@meta.data),"UMAP_1","UMAP_2")
df_out<- FetchData(srat_Control2,to_keep) %>% rownames_to_column("cell")
out_name <- paste0("./Control2_",Sys.Date(),"_cell_metadata.tsv.gz")
write_csv(df_out,out_name)
###############################################################################################
srat_Control3 <- subset(srat_QC,subset=sample.origin=="Control3")
#Pre-process sample Seurat object
srat_Control3 <- SCTransform(srat_Control3,verbose=F)
srat_Control3 <- RunPCA(srat_Control3, features = VariableFeatures(object = srat_Control3))
srat_Control3 <- FindNeighbors(srat_Control3, dims = 1:20)
srat_Control3 <- FindClusters(srat_Control3, resolution = 1)
srat_Control3 <- RunTSNE(srat_Control3)
srat_Control3 <- RunUMAP(srat_Control3, dims = 1:20)

#pK Identification
sweep.res.list_Control3 <- paramSweep(srat_Control3, PCs = 1:10, sct = T)
sweep.stats_Control3 <- summarizeSweep(sweep.res.list_Control3, GT = FALSE)
bcmvn_Control3 <- find.pK(sweep.stats_Control3)

pK_Control3 <- sweep.stats_Control3 %>% filter(BCreal == max(BCreal)) %>% select(pK) 
pK_Control3 <- as.numeric(as.character(pK_Control3[[1]]))
## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop_Control3 <- modelHomotypic(srat_Control3$SCT_snn_res.1)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi_Control3 <- round(0.024*nrow(srat_Control3@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj_Control3 <- round(nExp_poi_Control3*(1-homotypic.prop_Control3))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
srat_Control3 <- doubletFinder(srat_Control3, PCs = 1:10, pN = 0.25, pK = pK_Control3, nExp = nExp_poi_Control3, reuse.pANN = FALSE, sct = T)

saveRDS(srat_Control3,"srat_Control3.rds")
to_keep <- c(colnames(srat_Control3@meta.data),"UMAP_1","UMAP_2")
df_out<- FetchData(srat_Control3,to_keep) %>% rownames_to_column("cell")
out_name <- paste0("./Control3_",Sys.Date(),"_cell_metadata.tsv.gz")
write_csv(df_out,out_name)

###############################################################################################
srat_Control4 <- subset(srat_QC,subset=sample.origin=="Control4")
#Pre-process sample Seurat object
srat_Control4 <- SCTransform(srat_Control4,verbose=F)
srat_Control4 <- RunPCA(srat_Control4, features = VariableFeatures(object = srat_Control4))
srat_Control4 <- FindNeighbors(srat_Control4, dims = 1:20)
srat_Control4 <- FindClusters(srat_Control4, resolution = 1)
srat_Control4 <- RunTSNE(srat_Control4)
srat_Control4 <- RunUMAP(srat_Control4, dims = 1:20)

#pK Identification
sweep.res.list_Control4 <- paramSweep(srat_Control4, PCs = 1:10, sct = T)
sweep.stats_Control4 <- summarizeSweep(sweep.res.list_Control4, GT = FALSE)
bcmvn_Control4 <- find.pK(sweep.stats_Control4)

pK_Control4 <- sweep.stats_Control4 %>% filter(BCreal == max(BCreal)) %>% select(pK) 
pK_Control4 <- as.numeric(as.character(pK_Control4[[1]]))
## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
homotypic.prop_Control4 <- modelHomotypic(srat_Control4$SCT_snn_res.1)           ## ex: annotations <- seu_kidney@meta.data$ClusteringResults
nExp_poi_Control4 <- round(0.024*nrow(srat_Control4@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj_Control4 <- round(nExp_poi_Control4*(1-homotypic.prop_Control4))

## Run DoubletFinder with varying classification stringencies ----------------------------------------------------------------
srat_Control4 <- doubletFinder(srat_Control4, PCs = 1:10, pN = 0.25, pK = pK_Control4, nExp = nExp_poi_Control4, reuse.pANN = FALSE, sct = T)

saveRDS(srat_Control4,"srat_Control4.rds")
to_keep <- c(colnames(srat_Control4@meta.data),"UMAP_1","UMAP_2")
df_out<- FetchData(srat_Control4,to_keep) %>% rownames_to_column("cell")
out_name <- paste0("./Control4_",Sys.Date(),"_cell_metadata.tsv.gz")
write_csv(df_out,out_name)

```
